[build]
  publish = "dist"           # or your build output folder
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to   = "http://3.148.181.38:8080/api/:splat"
  status = 200
  force = true